// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomePageDocumentDataSlicesSlice = DescriptionTextSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Content for Portfolio Content documents
 */
interface PortfolioContentDocumentData {
  /**
   * Projects Pictures field in *Portfolio Content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_content.projects_pictures
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  projects_pictures: prismic.ImageField<never>;
}

/**
 * Portfolio Content document from Prismic
 *
 * - **API ID**: `portfolio_content`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioContentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PortfolioContentDocumentData>,
    "portfolio_content",
    Lang
  >;

export type AllDocumentTypes = HomePageDocument | PortfolioContentDocument;

/**
 * Primary content in *DescriptionText → Primary*
 */
export interface DescriptionTextSliceDefaultPrimary {
  /**
   * Sandwich Menu field in *DescriptionText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: description_text.primary.sandwich_menu
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  sandwich_menu: prismic.SelectField<"1" | "2">;
}

/**
 * Default variation for DescriptionText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DescriptionTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DescriptionText*
 */
type DescriptionTextSliceVariation = DescriptionTextSliceDefault;

/**
 * DescriptionText Shared Slice
 *
 * - **API ID**: `description_text`
 * - **Description**: DescriptionText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionTextSlice = prismic.SharedSlice<
  "description_text",
  DescriptionTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      PortfolioContentDocument,
      PortfolioContentDocumentData,
      AllDocumentTypes,
      DescriptionTextSlice,
      DescriptionTextSliceDefaultPrimary,
      DescriptionTextSliceVariation,
      DescriptionTextSliceDefault,
    };
  }
}
